Done implementing the required functions
edemagbenyo/private_events pull request #1
Opened 2020-01-10 00:16 UTC by edemagbenyo

2020-01-11 00:55 UTC, mosaaleb requested changes
## Well done Team :clap:

### Most requirements are handled, yet we need to work on other requirements before moving on:

- [x] Creating events with no user signed in breaks the application:

![fail](https://user-images.githubusercontent.com/4246637/72194913-78470080-3418-11ea-8efd-aaf681d83552.png)

we need to make sure that only logged in users can create or attend an event. We can restrict the request to creating and attending events routes by using [filters](https://guides.rubyonrails.org/action_controller_overview.html#filters).

In our case this could be something like in `events_controller`:
`before_action :require_login, only: [:action_name_here_that_you_want_to_restrict]`

and `require_login` can be defined in `application_controller` as:
```ruby
def require_login
  redirect_to signin_path unless logged_in?
end
```
This way If a logged out user tried to deliberately type `events/new` to create an event rails will redirect him to user sign in page.

We need also to apply this to event attendance functionality

- [ ] I can't find a way for a user to attend an event -- If you believe that you implemented this requirements, contact me on slack. Otherwise, please let's add it.


- [ ] We haven't written any rspec and capybara tests yet:

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png)

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png)

#### Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-01-11 00:55 UTC, mosaaleb commented on app/controllers/users_controller.rb
> +      redirect_to @user
- [ ] Let's sign in the user automatically after user creation.

2020-01-11 00:55 UTC, mosaaleb commented on app/views/events/index.html.erb
> +<% Event.past.each do |event| %>
- [ ] There should be no application logic in the views -- `Event.past` and `Event.future` are business logic and should not be here.
You are already sending instance variables from `index` action in `events_controller`.
Move the bussines logic in the controller as instance variable and use them directly in here.

2020-01-11 00:55 UTC, mosaaleb commented on app/views/events/show.html.erb
> +    <li><%= User.find_by(id: a.user_id).name %></li>
- [ ] Same here for business logic `User.find_by` shouldn't be in views.
Also we can simpley loop through `@event.attendees`, you have already defined an association for it in `event.rb`:
`has_many :attendees, through: :attendances`

2020-01-11 15:27 UTC, Grifo89 commented
@mosaaleb Can you show us where are those requirements you are talking about? remember you must stick on the requirements that are explicitly on the project page, not less not more, more must be optional.

2020-01-15 15:47 UTC, Grifo89 commented
Changes suggested are done!

2020-01-15 17:37 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

- You have to use Git Flow: Pull Requests from feature branches to the `develop` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/git_flow_requirement.png) from Pathwright).

- Pull Request should have a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).


### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-01-15 18:15 UTC, edemagbenyo commented
Hi @Redvanisation ,
About the creation of pull request using gitflow, It was a mistake from our part from the onset. It seems not clear how we can do that now that we have implemented the changes in the develop branch. Do you have any suggestions for us to correct it?

2020-01-15 20:09 UTC, closed without merging